/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-123978-g3b19a61837-20260416"
#endif /* AVUTIL_FFVERSION_H */
